package com.ggpk.studyload.service.impl;

/**
 * Created by dimmaryanto on 23/12/15.
 */
public enum LangProperties {
    ACTION("javafx.action.do"),
    ADD("javafx.action.add"),
    ARE_YOU_SURE("javafx.action.areyousure"),
    BACK("javafx.action.back"),
    BEING_PROCESSED("javafx.action.being.processed"),
    CANCEL("javafx.action.cancel"),
    YES("javafx.action.checkbox.checked"),
    NOT_YET("javafx.action.checkbox.unchecked"),
    CLEAR("javafx.action.clear"),
    CLEAR_SELECTION("javafx.action.clear.selection"),
    CLOSE("javafx.action.close"),
    DELETE("javafx.action.delete"),
    HIDE("javafx.action.hide"),
    HAS_BEEN_PROCESSED_WITH_PARAM("javafx.action.has.been.processed"),
    HAS_BEEN_PROCESSED("javafx.notification.warning.has.been.processed"),
    LOADING("javafx.action.load"),
    NEW_DATA("javafx.action.new"),
    NEXT("javafx.action.next"),
    PAYOFF("javafx.action.payoff"),
    POWER_OFF("javafx.action.power.off"),
    PRINT("javafx.action.print"),
    REFRESH("javafx.action.refresh"),
    REMOVE("javafx.action.remove"),
    SAVE("javafx.action.save"),
    SIGN_IN("javafx.action.sign.in"),
    SIGN_OUT("javafx.action.sign.out"),
    UPDATE("javafx.action.update"),
    VIEW("javafx.action.view"),
    ERROR_LOADING_WITH_PARAM("javafx.notification.error.loading"),
    ERROR_PRINT_WITH_PARAM("javafx.notification.error.print"),
    ERROR_REMOVE_WITH_PARAMS("javafx.notification.error.remove"),
    ERROR_SAVE_WITH_PARAM("javafx.notification.error.save"),
    ERROR_UPDATE_WITH_PARAMS("javafx.notification.error.update"),
    PROGRESS_FINISHED_WITH_PARAM("javafx.notification.progress.finish"),
    PROGRESS_GETTING_WITH_PARAMS("javafx.notification.progress.getting"),
    PROGRESS_LOADING_WITH_PARAM("javafx.notification.progress.loading"),
    QUESTION_REMOVE_WITH_PARAMS("javafx.notification.question.remove"),
    QUESTION_ARE_YOU_SURE("javafx.notification.question.sure"),
    SUCESSED_REMOVE_WITH_PARAM("javafx.notification.success.remove"),
    SUCESSED_SAVE_WITH_PARAM("javafx.notification.success.save"),
    SUCESSED_SAVE("javafx.notification.success.saved"),
    SUCESSED_SAVE_WITH_PARAMS("javafx.notification.success.save.item"),
    SUCESSED_UPDATE_WITH_PARAM("javafx.notification.success.update"),
    SUCESSED_UPDATE_WITH_PARAMS("javafx.notification.success.update.item"),
    CANT_REMOVE_SENT_WITH_PARAM("javafx.notification.warning.cant.remove.sent"),
    EXPIRED_DATE_WITH_PARAM("javafx.notification.warning.expired"),
    NOT_ENOUGH_WITH_PARAM("javafx.notification.warning.not-enough"),
    NOT_NULL_WITH_PARAM("javafx.notification.warning.notnull"),
    ON_PROGRESS("javafx.notification.warning.on.progress"),
    HAS_BEEN_PAID_WITH_PARAM("javafx.notification.warning.paid"),
    HAS_BEEN_SEND_WITH_PARAM("javafx.notification.warning.sent"),
    DATE_NOT_EQUAL_NOW("javafx.validation.date-equal-not-now"),
    EMPTY_WITH_PARAM("javafx.validation.empty"),
    MIN_WITH_PARAM("javafx.validation.min"),
    MIN_MAX_WITH_PARAMS("javafx.validation.min-max"),
    NOT_SELECTED_WITH_PARAM("javafx.validation.not-selected"),
    NULL_WITH_PARAM("javafx.validation.null"),
    MAIN_MENU("scene.home.menu"),
    MENU_APPLICATION("scene.home.menu.application"),
    EXIT("scene.home.menu.application.exit"),
    LOGIN("scene.home.menu.application.login"),
    LOGOUT("scene.home.menu.application.logout"),
    HELP("scene.home.menu.help"),
    CONTACT("scene.home.menu.help"),
    LIST_OF_DISCIPLINES("scene.home.menu.master.plan"),
    LIST_OF_DISCIPLINES_LOADING("scene.home.menu.master.plan.load"),
    DATA_AN_ACCOUNT("scene.home.menu.setting.account.an-account"),
    IS_ACTIVE("java.model.account.is.active"),
    ID("java.model.id"),
    NOT_YET_RECEIVED("javafx.notification.warning.not.yet.received"),
    NOT_YET_RECEIVED_WITH_PARAM("javafx.notification.warning.not.yet.received.item"),
    ALREADY_RECEIVED("javafx.notification.warning.already.received"),
    ALREADY_RECEIVED_WITH_PARAM("javafx.notification.warning.already.received.item"),
    HAS_BEEN_CALCULATED("javafx.notification.warning.has.been.calculated"),
    WILL_NOT_BE_COUNTED("javafx.notification.warning.will.not.be.counted"),
    IS_EMPTY_WITH_PARAM("javafx.notification.warning.empty"),
    YET_CALCULATED("javafx.notification.warning.yet.calculated"),
    SYSTEM_INFORMATION_TRANSACTION_OF_INCOME_AND_EXPENDITUR("scene.home.header.title"),
    SOON_TO_BE_REPAID("javafx.notification.warning.soon.to.be.repaid"),
    FINANCIAL_STATEMENT("scene.home.menu.report.financial.statement"),
    UNPROCESSED("scene.financial.statement.unprocessed"),
    TOTAL_TRANSACTION_REVENUES("scene.financial.statement.total.revenues"),
    TOTAL_NET_INCOME("scene.financial.statement.total.net.income"),
    TOTAL_ACCOUNTS_RECIEVABLE("scene.financial.statement.total.accounts.recievable"),
    WILL_BE_CALCULATED("javafx.notification.warning.will.be.calculated"),
    AUTHENTICATION_FAILED("javafx.notification.warning.authentication.failed"),
    THIS_ACCOUNT_NOT_ACTIVE("javafx.notification.warning.account.not.active"),
    DISABLED("javafx.action.disabled"),
    ACTIVATED("javafx.action.activated"),
    PROTECTED("javafx.action.protected"),
    FORBIDDEN("javafx.action.forbidden"),
    QTY_OF_ITEM_LESS_THAN_PARAMS("javafx.notification.warning.item.min"),
    PROCESS("javafx.action.processed"),
    NOT_READY("javafx.action.not.ready"),
    DATA_DISCIPLINE("java.model.discipline.name"),
    DATA_DISCIPLINE_DELETE("java.model.discipline.name.delete");


    private final String value;

    LangProperties(String s) {
        this.value = s;
    }

    public String getValue() {
        return value;
    }
}
